"""
Builder Agent — Executor Sub-agent
------------------------------------
Runs a Builder trial script as an isolated subprocess and returns a TrialResult.

The Executor:
- Receives the path to a Python script generated by the Coder sub-agent
- Runs it via subprocess.run() with a 10-minute timeout
- Reads the output JSON written by the script to results/trial_{trial_id}.json
- Returns a TrialResult (with error set if the process failed or timed out)

CRITICAL: Never runs two trials simultaneously — strictly sequential execution.
CRITICAL: Reads RAM from the trial's output JSON, not from the subprocess itself.
CRITICAL: If Nielsen data is not found, returns a clear error without fabricating data.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Optional

from .experiment_registry import TrialConfig, TrialResult

RESULTS_DIR = Path("results")
TIMEOUT_SECONDS = 600   # 10 minutes per trial


class Executor:
    """
    Runs a Coder-generated trial script in an isolated subprocess and captures results.

    Usage
    -----
    >>> executor = Executor()
    >>> result = executor.run(script_path="results/scripts/trial_t001.py", config=config)
    """

    def __init__(
        self,
        results_dir: Path = RESULTS_DIR,
        timeout: int = TIMEOUT_SECONDS,
        python_executable: str = sys.executable,
    ) -> None:
        self.results_dir = results_dir
        self.timeout = timeout
        self.python = python_executable

    def run(self, script_path: str, config: TrialConfig) -> TrialResult:
        """
        Execute the trial script as a subprocess and return a TrialResult.

        The script is expected to:
        1. Run Phase 2 + Phase 3 of System A with the given TrialConfig
        2. Write results to results/trial_{trial_id}.json

        Parameters
        ----------
        script_path : str
            Path to the Python script generated by the Coder sub-agent.
        config : TrialConfig
            The configuration being tested. Used to locate the output JSON.

        Returns
        -------
        TrialResult
            Populated from the output JSON on success, or with error set on failure.
        """
        trial_id = config["trial_id"]
        output_path = self.results_dir / f"trial_{trial_id}.json"

        empty_result: TrialResult = {
            "trial_id": trial_id,
            "MAPE": 0.0,
            "RMSE": 0.0,
            "peak_RAM_MB": 0.0,
            "latency_sec": 0.0,
            "confidence_score": 0.0,
            "error": None,
        }

        # ── Run subprocess ────────────────────────────────────────────────────
        try:
            proc = subprocess.run(
                [self.python, script_path],
                timeout=self.timeout,
                capture_output=True,
                text=True,
            )
        except subprocess.TimeoutExpired:
            return {
                **empty_result,
                "error": (
                    f"Trial {trial_id} timed out after {self.timeout}s. "
                    "Consider reducing model complexity or increasing timeout."
                ),
            }
        except FileNotFoundError:
            return {
                **empty_result,
                "error": (
                    f"Script not found: {script_path}. "
                    "Coder sub-agent must create the script before Executor runs."
                ),
            }

        # ── Read output JSON ──────────────────────────────────────────────────
        if output_path.exists():
            try:
                data = json.loads(output_path.read_text())
                result: TrialResult = {
                    "trial_id": data.get("trial_id", trial_id),
                    "MAPE": float(data.get("MAPE", 0.0)),
                    "RMSE": float(data.get("RMSE", 0.0)),
                    "peak_RAM_MB": float(data.get("peak_RAM_MB", 0.0)),
                    "latency_sec": float(data.get("latency_sec", 0.0)),
                    "confidence_score": float(data.get("confidence_score", 0.0)),
                    "error": data.get("error"),
                }
                return result
            except (json.JSONDecodeError, KeyError, TypeError) as exc:
                return {
                    **empty_result,
                    "error": f"Output JSON malformed for trial {trial_id}: {exc}",
                }

        # ── Subprocess failed without writing output ───────────────────────────
        if proc.returncode != 0:
            stderr = proc.stderr.strip() if proc.stderr else "(no stderr)"
            # Special-case: Nielsen data missing — propagate clear message
            if "Nielsen data not found" in stderr or "Feature matrix not found" in stderr:
                return {
                    **empty_result,
                    "error": (
                        "Nielsen data not found at data/nielsen/ — "
                        "trials cannot run until data is available. "
                        f"Original error: {stderr}"
                    ),
                }
            return {
                **empty_result,
                "error": f"Trial script exited with code {proc.returncode}. stderr: {stderr}",
            }

        return {
            **empty_result,
            "error": (
                f"Trial {trial_id} completed (returncode=0) but did not write output to "
                f"{output_path}. Script may be missing the write_output() call."
            ),
        }

    def validate_ram(self, result: TrialResult, limit_mb: float = 7_680.0) -> Optional[str]:
        """
        Check whether the trial's peak RAM exceeded the 7.5 GB Builder limit.

        Parameters
        ----------
        result : TrialResult
            Result produced by run().
        limit_mb : float
            RAM limit in MB (default 7,680 = 7.5 GB).

        Returns
        -------
        str or None
            Error message if the limit was exceeded; None if within budget.
        """
        if result["peak_RAM_MB"] > limit_mb:
            return (
                f"Trial {result['trial_id']} exceeded RAM limit: "
                f"{result['peak_RAM_MB']:.0f} MB > {limit_mb:.0f} MB. "
                "Architect must not propose this configuration again."
            )
        return None
