#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
split_thesis_pdf.py -- Split the thesis PDF into per-chapter or per-section PDFs.

Reads the PDF's own bookmark outline -- the structure Word wrote from the
heading styles -- so chapter and section boundaries are the document's, not a
heuristic over extracted text. Writes one PDF per unit plus an index table
(`00_INDEX.md`) recording every page range, so the table and the files on disk
cannot disagree: both come from the same run.

Two split modes:

  --chapters-only   (default)  one PDF per level-1 heading
  --chapters-and-h2            one PDF per level-2 section, plus one per
                               level-1 heading that has no level-2 children

The second mode deliberately does NOT also emit a whole-chapter PDF for
chapters that have sections: that would publish every page twice, and a
chapter is reconstructible by concatenating its sections. Level-3 headings are
never split -- too many, too small.

A note on one real boundary case. A section can begin on the same physical page
its next chapter begins on (in the 2026-09-14 draft, `5.7 Connection to SRQs`
and `Chapter 6` both start on page 85). Sections are therefore clamped to their
own chapter's page range, which means such a page legitimately appears in two
files. That is a property of the document, not a bug in the split: the page
carries the end of one chapter and the start of the next. `--report-overlaps`
lists every instance.
"""

from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

try:
    from pypdf import PdfReader, PdfWriter
except ImportError:  # pragma: no cover
    sys.exit("pypdf is required:  python -m pip install pypdf")

# Anchor on a repo marker rather than a hop-count; parents[N] breaks the moment
# this file moves a level, and it has moved before (see path-handling.md).
for _cand in (Path(__file__).resolve().parent, *Path(__file__).resolve().parents):
    if any((_cand / _a).exists() for _a in (".env.example", ".env", "PATHS.py")):
        _REPO_ROOT = _cand
        if str(_cand) not in sys.path:
            sys.path.insert(0, str(_cand))
        break
else:  # pragma: no cover
    raise FileNotFoundError("Could not find project root above " + str(Path(__file__).resolve()))

# Front matter that is auto-generated by Word and worthless as a lookup PDF.
# Matched on the normalised heading text, so a renumbering does not break it.
FRONT_MATTER = {
    "tableofcontents",
    "tableoffigures",
    "tableoftables",
    "tableofappendices",
}

STEM_PREFIX = "Thesis"
INDEX_NAME = "00_INDEX.md"
MAX_TITLE_CHARS = 60


@dataclass
class Unit:
    """One thing that becomes one PDF."""

    level: int
    chapter_no: int | None  # None for unnumbered blocks (Abstract, Appendix...)
    chapter_title: str
    section_no: str | None  # "5.5.7" style, None for whole-chapter units
    title: str
    start: int  # 1-based, inclusive
    end: int = 0  # 1-based, inclusive; filled in later
    overlaps: list[str] = field(default_factory=list)

    @property
    def pages(self) -> int:
        return self.end - self.start + 1


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _slug(text: str, limit: int = MAX_TITLE_CHARS) -> str:
    """Filesystem-safe title fragment: ASCII, underscores, no punctuation."""
    # Decompose accents rather than dropping the letters outright, so
    # "Danskvand" survives and an en-dash does not become a word boundary.
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = text.replace("&", "and")
    text = re.sub(r"[‐-―]", "-", text)  # unicode dashes -> hyphen
    text = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")
    if len(text) > limit:
        text = text[:limit].rstrip("_")
    return text or "untitled"


def _split_heading(title: str) -> tuple[int | None, str | None, str]:
    """Return (chapter_no, section_no, clean_title) for an outline heading.

    Handles 'Chapter 5 | Model Benchmark & Selection' and '5.5.7 Calibration'.
    """
    m = re.match(r"^Chapter\s+(\d+)\s*[|:\-–—]?\s*(.*)$", title, re.I)
    if m:
        return int(m.group(1)), None, m.group(2).strip() or f"Chapter {m.group(1)}"
    m = re.match(r"^(\d+(?:\.\d+)*)\s+(.*)$", title)
    if m:
        num = m.group(1)
        return int(num.split(".")[0]), num, m.group(2).strip()
    return None, None, title.strip()


def read_outline(reader: PdfReader) -> list[tuple[int, int, str]]:
    """Flatten the bookmark tree to (level, 1-based page, title)."""
    rows: list[tuple[int, int, str]] = []

    def walk(items, depth: int = 0) -> None:
        for it in items:
            if isinstance(it, list):
                walk(it, depth + 1)
                continue
            try:
                page = reader.get_destination_page_number(it) + 1
            except Exception:
                continue
            title = re.sub(r"\s+", " ", str(it.title)).strip()
            if title:
                rows.append((depth, page, title))

    if not reader.outline:
        sys.exit("This PDF has no bookmark outline; cannot determine chapters.")
    walk(reader.outline)
    return rows


def build_units(rows, total_pages: int, mode: str, keep_front: bool) -> list[Unit]:
    h1 = [(p, t) for lvl, p, t in rows if lvl == 0]
    if not h1:
        sys.exit("No level-1 headings found in the outline.")

    units: list[Unit] = []

    for i, (start, title) in enumerate(h1):
        ch_end = (h1[i + 1][0] - 1) if i + 1 < len(h1) else total_pages
        ch_no, _, clean = _split_heading(title)

        if not keep_front and _norm(title) in FRONT_MATTER:
            continue

        # Level-2 children that fall inside this chapter's page span. Bounded by
        # the chapter range rather than by the next H2, so a stray bookmark
        # cannot pull a section into the wrong chapter.
        kids = [
            (p, t)
            for lvl, p, t in rows
            if lvl == 1 and start <= p <= ch_end
        ]

        # A single unnumbered child (e.g. the Appendix's one subheading) is not
        # a section split -- splitting there would name the whole block after
        # its first subheading and lose the block's own name. Keep it whole.
        only_unnumbered_child = (
            len(kids) == 1 and _split_heading(kids[0][1])[1] is None
        )

        if mode == "chapters-only" or not kids or only_unnumbered_child:
            units.append(
                Unit(1, ch_no, clean, None, clean, start, ch_end)
            )
            continue

        # One unit per section. The first section may begin after the chapter's
        # own start page (a title page); those pages would otherwise be lost, so
        # the first section is extended back to the chapter start.
        for k, (kstart, ktitle) in enumerate(kids):
            kend = (kids[k + 1][0] - 1) if k + 1 < len(kids) else ch_end
            sec_ch, sec_no, sec_title = _split_heading(ktitle)
            units.append(
                Unit(
                    level=2,
                    chapter_no=sec_ch if sec_ch is not None else ch_no,
                    chapter_title=clean,
                    section_no=sec_no,
                    title=sec_title,
                    start=start if k == 0 else kstart,
                    end=max(kend, kstart),
                )
            )

    _mark_overlaps(units)
    return units


def _mark_overlaps(units: list[Unit]) -> None:
    """Record, per unit, which pages it shares with which other unit.

    Built from a page -> claimants map rather than by comparing ranges
    pairwise. An earlier pairwise version silently reported zero overlaps on a
    document that had nine, which is worse than not checking: an empty
    "Shared pages" section reads as a clean bill of health.
    """
    claims: dict[int, list[Unit]] = {}
    for u in units:
        for p in range(u.start, u.end + 1):
            claims.setdefault(p, []).append(u)

    shared: dict[tuple[int, int], list[int]] = {}
    for page, owners in claims.items():
        if len(owners) < 2:
            continue
        for i, a in enumerate(owners):
            for b in owners[i + 1:]:
                shared.setdefault((id(a), id(b)), []).append(page)

    by_id = {id(u): u for u in units}
    for (ida, idb), pages in shared.items():
        a, b = by_id[ida], by_id[idb]
        span = f"p{min(pages)}" if len(pages) == 1 else f"p{min(pages)}-{max(pages)}"
        a.overlaps.append(f"{span} with `{_stem(b)}.pdf`")
        b.overlaps.append(f"{span} with `{_stem(a)}.pdf`")


def _stem(u: Unit) -> str:
    """Thesis-Ch05-5.5.7-Prediction_interval_calibration"""
    if u.chapter_no is not None:
        ch = f"Ch{u.chapter_no:02d}"
    else:
        ch = "Ch00"
    parts = [STEM_PREFIX, ch]
    if u.section_no:
        parts.append(u.section_no)
    parts.append(_slug(u.title))
    return "-".join(parts)


Unit.stem = lambda self: _stem(self)  # type: ignore[attr-defined]


def write_pdfs(reader: PdfReader, units: list[Unit], out_dir: Path, dry_run: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for u in units:
        name = f"{_stem(u)}.pdf"
        if dry_run:
            continue
        writer = PdfWriter()
        for p in range(u.start - 1, u.end):
            writer.add_page(reader.pages[p])
        with open(out_dir / name, "wb") as fh:
            writer.write(fh)


def write_index(units: list[Unit], out_dir: Path, src: Path, total: int, mode: str) -> Path:
    covered = set()
    for u in units:
        covered.update(range(u.start, u.end + 1))
    missing = sorted(set(range(1, total + 1)) - covered)
    overlapping = [u for u in units if u.overlaps]

    lines: list[str] = []
    lines.append(f"# Thesis PDF split index")
    lines.append("")
    lines.append(f"Generated by `utility_scripts/scripts/split_thesis_pdf.py` (`--{mode}`).")
    lines.append("**Do not edit by hand** — re-run the script instead.")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| Source | `{src.name}` |")
    lines.append(f"| Source pages | **{total}** |")
    lines.append(f"| Files written | **{len(units)}** |")
    lines.append(f"| Pages covered | **{len(covered)}** of {total} |")
    lines.append(f"| Pages in no file | **{len(missing)}**"
                 + (f" ({', '.join(str(m) for m in missing)})" if missing else "") + " |")
    lines.append("")

    lines.append("## Files")
    lines.append("")
    lines.append("| Chapter | Section | Title | Pages | Count | Filename |")
    lines.append("|---|---|---|---|---:|---|")
    for u in units:
        ch = f"{u.chapter_no}" if u.chapter_no is not None else "—"
        sec = u.section_no or "—"
        rng = f"{u.start}" if u.start == u.end else f"{u.start}–{u.end}"
        title = u.title.replace("|", r"\|")
        lines.append(f"| {ch} | {sec} | {title} | {rng} | {u.pages} | `{_stem(u)}.pdf` |")
    lines.append("")

    if overlapping:
        lines.append("## Shared pages")
        lines.append("")
        lines.append(
            "A page appears in two files when a section ends on the same page the "
            "next chapter begins. The page carries content belonging to both, so "
            "both files need it — this is a property of the document, not a split error."
        )
        lines.append("")
        lines.append("| File | Shares |")
        lines.append("|---|---|")
        for u in overlapping:
            lines.append(f"| `{_stem(u)}.pdf` | {'; '.join(u.overlaps)} |")
        lines.append("")

    path = out_dir / INDEX_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    path.write_bytes("\n".join(lines).encode("utf-8"))
    return path


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Split the thesis PDF into per-chapter or per-section PDFs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("pdf", type=Path, help="path to the thesis PDF")
    ap.add_argument("-o", "--out-dir", type=Path, default=None,
                    help="output directory (default: <pdf stem>_split beside the PDF)")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--chapters-only", dest="mode", action="store_const",
                   const="chapters-only", help="one PDF per chapter (default)")
    g.add_argument("--chapters-and-h2", dest="mode", action="store_const",
                   const="chapters-and-h2",
                   help="one PDF per H2 section, plus whole-chapter PDFs for "
                        "chapters that have no H2")
    ap.add_argument("--include-front-matter", action="store_true",
                    help="also split Table of Contents/Figures/Tables/Appendices")
    ap.add_argument("--dry-run", action="store_true",
                    help="write only the index; produce no PDFs")
    ap.set_defaults(mode="chapters-only")
    args = ap.parse_args()

    if not args.pdf.is_file():
        sys.exit(f"No such file: {args.pdf}")

    reader = PdfReader(str(args.pdf))
    total = len(reader.pages)
    rows = read_outline(reader)
    units = build_units(rows, total, args.mode, args.include_front_matter)

    out_dir = args.out_dir or args.pdf.parent / f"{args.pdf.stem}_split"
    write_pdfs(reader, units, out_dir, args.dry_run)
    index = write_index(units, out_dir, args.pdf, total, args.mode)

    covered = set()
    for u in units:
        covered.update(range(u.start, u.end + 1))
    print(f"  mode     : {args.mode}")
    print(f"  source   : {args.pdf.name} ({total} pages)")
    print(f"  units    : {len(units)}")
    print(f"  coverage : {len(covered)}/{total} pages")
    if args.dry_run:
        print("  DRY RUN  : no PDFs written")
    else:
        print(f"  written  : {out_dir}")
    print(f"  index    : {index}")


if __name__ == "__main__":
    main()
